#!/bin/bash

REGEX_ISSUE_ID="^(ACE-[0-9]+|Merge|hotfix)"
ISSUE_ID_IN_COMMIT=$(echo $(cat "$1") | grep -o -E "$REGEX_ISSUE_ID")

if [[ -z "$ISSUE_ID_IN_COMMIT" ]]; then
    echo "Your commit message should have Jira ticket number"
    exit 1
fi